defaults:
  - _self_
  - experiment: null
  # - override hydra/job_logging: colorlog
  # - override hydra/hydra_logging: colorlog

# Default set of configurations.
data_dir: ???
results_dir: ???
lr: 0.1
batch_size: 64
n_bits: 8
num_workers: 8
temperature_leaves: 1.0
temperature_sums: 1.0
dropout: 0.0
min_sigma: 1e-2
max_sigma: 2.0
dry_run: False
seed: 1
log_interval: 10
classification: True
device: "cuda"
debug: False
S: 10
I: 10
M: 1
D: 3
R: 1
gpu: 0
epochs: 10
load_and_eval: False
cp: True
dist: "classnormal"
precision: 16
group_tag: ???
tag: ???
wandb: True
swa: True
profiler: ???
log_weights: False
dataset: cifar
num_classes: 10
weight_decay: 0
weight_decay_decay: 1
num_steps_per_epoch: None
leaf_dropout: 0
sum_dropout: 0.0 # problem of no gradient if only one component
tau: 0.0
tau_decay: 1
noise_std: 0.0
gradient_clip_val: 0
learn_permutations: False
sinkhorn_tau: 1
switch_permutation: False
permutation_lr: 0.99
permutation_switch_step_ratio_denominator: 8
independent_colors: True
shuffle_features: True
mixing_depth: 1
num_hidden_mixtures: None